apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: movie-library
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: movie-library
    template:
      ref: movie-library