apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scan-code
  namespace: projeto-fenix
spec:
  params:
    - default: 'quay.io/rhn_support_rpinto/sonar-cli-demo:latest'
      name: scanImage
      type: string
    - default: >-
        https://sonarqube-projeto-sonarqube.apps.230705-lab.sandbox812.opentlc.com/
      name: sonarqubeHostUrl
      type: string
    - default: projeto-fenix
      name: sonarqubeProjectKey
      type: string
    - default: projeto-fenix-sonarqube-secret
      name: sonarqubeProjectSecret
      type: string
    - default: 'true'
      name: verbose
      type: string
  steps:
    - env:
        - name: SONAR_TOKEN_WEB_UI
          valueFrom:
            secretKeyRef:
              key: token
              name: $(params.sonarqubeProjectSecret)
      image: $(params.scanImage)
      name: scan-code
      resources: {}
      script: >
        set -x

        echo $(ls -a)

        sonar-scanner -Dsonar.projectKey=$(params.sonarqubeProjectKey)
        -Dsonar.host.url=$(params.sonarqubeHostUrl)
        -Dsonar.token=$SONAR_TOKEN_WEB_UI  -Dsonar.qualitygate.wait=true
        -Dsonar.sources=src/main/java -Dsonar.java.binaries=target/classes
        -Dsonar.java.libraries=target/quarkus-app/lib
        -Dsonar.java.test.binaries=target/test-classes
        -Dsonar.projectVersion=1.0
      workingDir: /workspace/repository
  workspaces:
    - name: repository
