resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d5da4349c068c307e413b38c85697f15cf3b63038a901dbbed36ea01fcb9d334
  name: quay.io/gtavares_pessoal/movie-library-app
