resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:830aebb2c12b09e9b9c1c6423b9da38e8c11f61b7f1ac25d0bd667e2b1ef1090
  name: quay.io/gtavares_pessoal/movie-library-app
